version: '3'
services:
  consumidor:
    build: ./ms-consumidor
    container_name: ms-consumidor
    environment:
      - "NODE_PORT=3000"
      - "PORTA_KAFKA=9092"      
    ports: 
      - 3000:3000
    restart: on-failure

  fornecedor:
    build: ./ms-fornecedor
    container_name: ms-fornecedor
    environment:
      - "NODE_PORT=3001"
      - "PORTA_KAFKA=9092"
    ports: 
      - 3001:3001
    restart: on-failure

  produto:
    build: ./ms-produto
    container_name: ms-produto
    environment:
      - "NODE_PORT=3002"
      - "PORTA_KAFKA=9092"
    ports: 
      - 3002:3002
    restart: on-failure

  web:
    build: ./ms-web
    container_name: ms-web
    ports: 
      - 3003:80
    restart: on-failure