version: '3'
services:
  produto:
    build: ./ms-produto
    container_name: ms-produto
    environment:
      - "NODE_PORT=3002"
      - "PORTA_KAFKA=9092"      
    ports: 
      - 3002:3002
    restart: on-failure
    volumes:
      - ./ms-produto:/usr/ms-produto
  web:
    build: ./ms-web
    container_name: ms-web
    ports: 
      - 3003:80
    restart: on-failure